"""
Master Design System (MDS) — Canonical Subsystem Registry
Phase 9.7.10: Unified Local Orchestrator CLI & Master Validation Pipeline
Lead Architect: Mohamed Khalid (Senior Full Stack & Flutter Developer)
"""

from __future__ import annotations

from typing import Dict, List, Optional
from .models import SubsystemDefinition, ExecutionCategory

ORCHESTRATOR_SUBSYSTEM_REGISTRY: Dict[str, SubsystemDefinition] = {
    "SUB-01": SubsystemDefinition(
        subsystem_id="SUB-01",
        subsystem_name="Historical Phase Guard",
        owning_phase="Phase 9.7.9",
        stage=1,
        dependencies=[],
        entrypoint="historical_guard.engine:HistoricalGuardEngine",
        assertion_namespace="TEST-HST-*",
        result_contract="HistoricalVerificationResult",
        supported_profiles=["fast", "core", "full", "ci"],
        execution_category=ExecutionCategory.MANDATORY_SAFETY_GATE,
    ),
    "SUB-02": SubsystemDefinition(
        subsystem_id="SUB-02",
        subsystem_name="Governance Invariants Engine",
        owning_phase="Phase 9.7.8",
        stage=1,
        dependencies=["SUB-01"],
        entrypoint="governance.engine:GovernanceEngine",
        assertion_namespace="INV-001..012",
        result_contract="GovernanceResult",
        supported_profiles=["fast", "core", "full", "ci"],
        execution_category=ExecutionCategory.MANDATORY_SAFETY_GATE,
    ),
    "SUB-03": SubsystemDefinition(
        subsystem_id="SUB-03",
        subsystem_name="Capability Registry Validator",
        owning_phase="Phase 9.7.8",
        stage=1,
        dependencies=[],
        entrypoint="registry.validator:RegistryValidator",
        assertion_namespace="MDS-REG-*",
        result_contract="ValidationResult",
        supported_profiles=["fast", "core", "full", "ci"],
        execution_category=ExecutionCategory.MANDATORY_SAFETY_GATE,
    ),
    "SUB-04": SubsystemDefinition(
        subsystem_id="SUB-04",
        subsystem_name="Repository Structure Validator",
        owning_phase="Phase 8.1",
        stage=1,
        dependencies=[],
        entrypoint="static.repo_validator:RepoValidator",
        assertion_namespace="MDS-REP-*",
        result_contract="RepoValidationResult",
        supported_profiles=["fast", "core", "full", "ci"],
        execution_category=ExecutionCategory.MANDATORY_SAFETY_GATE,
    ),
    "SUB-05": SubsystemDefinition(
        subsystem_id="SUB-05",
        subsystem_name="Token DTCG Parser & Schema",
        owning_phase="Phase 9.2",
        stage=2,
        dependencies=["SUB-04"],
        entrypoint="governance.dtcg_parser:DTCGTokenParser",
        assertion_namespace="MDS-TKN-*",
        result_contract="TokenValidationResult",
        supported_profiles=["fast", "core", "full", "ci"],
        execution_category=ExecutionCategory.CORE_SPECIFICATION,
    ),
    "SUB-06": SubsystemDefinition(
        subsystem_id="SUB-06",
        subsystem_name="Semantic CSS Scanner",
        owning_phase="Phase 9.1",
        stage=2,
        dependencies=["SUB-05"],
        entrypoint="static.css_scanner:CSSScanner",
        assertion_namespace="MDS-CSS-*",
        result_contract="CSSScanResult",
        supported_profiles=["fast", "core", "full", "ci"],
        execution_category=ExecutionCategory.CORE_SPECIFICATION,
    ),
    "SUB-07": SubsystemDefinition(
        subsystem_id="SUB-07",
        subsystem_name="DSSE Mathematical Harness",
        owning_phase="Phase 8.5",
        stage=2,
        dependencies=[],
        entrypoint="test_dsse:TestDSSEValidation",
        assertion_namespace="MDS-DSS-*",
        result_contract="DSSEResult",
        supported_profiles=["fast", "core", "full", "ci"],
        execution_category=ExecutionCategory.CORE_SPECIFICATION,
    ),
    "SUB-08": SubsystemDefinition(
        subsystem_id="SUB-08",
        subsystem_name="Core Primitives Contract Suite",
        owning_phase="Phase 9.3",
        stage=3,
        dependencies=["SUB-05"],
        entrypoint="run_tests:MDSTestRunner.run_primitive_tests",
        assertion_namespace="MDS-PRI-001..004",
        result_contract="ContractResult",
        supported_profiles=["core", "full", "ci"],
        execution_category=ExecutionCategory.CONTRACT_INVARIANT,
    ),
    "SUB-09": SubsystemDefinition(
        subsystem_id="SUB-09",
        subsystem_name="Core Components Contract Suite",
        owning_phase="Phase 9.4",
        stage=3,
        dependencies=["SUB-08"],
        entrypoint="run_tests:MDSTestRunner.run_component_tests",
        assertion_namespace="MDS-CMP-001..004",
        result_contract="ContractResult",
        supported_profiles=["core", "full", "ci"],
        execution_category=ExecutionCategory.CONTRACT_INVARIANT,
    ),
    "SUB-10": SubsystemDefinition(
        subsystem_id="SUB-10",
        subsystem_name="Patterns & Templates Laws",
        owning_phase="Phase 9.5",
        stage=3,
        dependencies=["SUB-09"],
        entrypoint="run_tests:MDSTestRunner.run_pattern_tests",
        assertion_namespace="MDS-PAT-*",
        result_contract="CompositionResult",
        supported_profiles=["core", "full", "ci"],
        execution_category=ExecutionCategory.CONTRACT_INVARIANT,
    ),
    "SUB-11": SubsystemDefinition(
        subsystem_id="SUB-11",
        subsystem_name="Workflow FSM Determinism",
        owning_phase="Phase 9.6",
        stage=3,
        dependencies=["SUB-09"],
        entrypoint="run_tests:MDSTestRunner.run_workflow_tests",
        assertion_namespace="MDS-WKF-001..004",
        result_contract="WorkflowResult",
        supported_profiles=["core", "full", "ci"],
        execution_category=ExecutionCategory.CONTRACT_INVARIANT,
    ),
    "SUB-12": SubsystemDefinition(
        subsystem_id="SUB-12",
        subsystem_name="Browser & Server Infrastructure",
        owning_phase="Phase 9.7.3",
        stage=4,
        dependencies=["SUB-04"],
        entrypoint="browser.browser_discovery:BrowserDiscovery",
        assertion_namespace="MDS-SRV-*",
        result_contract="ServerSessionResult",
        supported_profiles=["full", "ci"],
        execution_category=ExecutionCategory.DYNAMIC_INFRASTRUCTURE,
    ),
    "SUB-13": SubsystemDefinition(
        subsystem_id="SUB-13",
        subsystem_name="Live Accessibility & Axe-Core",
        owning_phase="Phase 9.7.5",
        stage=4,
        dependencies=["SUB-12"],
        entrypoint="accessibility.accessibility_dispatch:AccessibilityDispatcher",
        assertion_namespace="MDS-A11Y-001..004",
        result_contract="AccessibilityResult",
        supported_profiles=["full", "ci"],
        execution_category=ExecutionCategory.DYNAMIC_LIVE,
    ),
    "SUB-14": SubsystemDefinition(
        subsystem_id="SUB-14",
        subsystem_name="Responsive Viewport Matrix",
        owning_phase="Phase 9.7.6",
        stage=4,
        dependencies=["SUB-12"],
        entrypoint="responsive.responsive_dispatch:ResponsiveDispatcher",
        assertion_namespace="MDS-RWD-001..003",
        result_contract="ResponsiveResult",
        supported_profiles=["full", "ci"],
        execution_category=ExecutionCategory.DYNAMIC_LIVE,
    ),
    "SUB-15": SubsystemDefinition(
        subsystem_id="SUB-15",
        subsystem_name="Visual Regression Pixel-Diff",
        owning_phase="Phase 9.7.7",
        stage=4,
        dependencies=["SUB-12"],
        entrypoint="visual.visual_dispatch:VisualDispatcher",
        assertion_namespace="MDS-VIS-001",
        result_contract="VisualResult",
        supported_profiles=["full", "ci"],
        execution_category=ExecutionCategory.DYNAMIC_LIVE,
    ),
}

MANDATORY_SAFETY_GATES = [
    "SUB-01",  # Historical Phase Guard
    "SUB-04",  # Repo Structure
    "SUB-03",  # Capability Registry
    "SUB-02",  # Governance Engine
]

NAME_TO_ID_MAP = {
    "historical": "SUB-01",
    "historical_guard": "SUB-01",
    "sub-01": "SUB-01",
    "governance": "SUB-02",
    "governance_engine": "SUB-02",
    "sub-02": "SUB-02",
    "registry": "SUB-03",
    "capability_registry": "SUB-03",
    "sub-03": "SUB-03",
    "repo": "SUB-04",
    "repository": "SUB-04",
    "sub-04": "SUB-04",
    "tokens": "SUB-05",
    "token": "SUB-05",
    "dtcg": "SUB-05",
    "sub-05": "SUB-05",
    "css": "SUB-06",
    "css_scanner": "SUB-06",
    "sub-06": "SUB-06",
    "dsse": "SUB-07",
    "sub-07": "SUB-07",
    "primitives": "SUB-08",
    "primitive": "SUB-08",
    "sub-08": "SUB-08",
    "components": "SUB-09",
    "component": "SUB-09",
    "sub-09": "SUB-09",
    "patterns": "SUB-10",
    "templates": "SUB-10",
    "sub-10": "SUB-10",
    "workflows": "SUB-11",
    "workflow": "SUB-11",
    "sub-11": "SUB-11",
    "browser": "SUB-12",
    "server": "SUB-12",
    "sub-12": "SUB-12",
    "accessibility": "SUB-13",
    "a11y": "SUB-13",
    "axe": "SUB-13",
    "sub-13": "SUB-13",
    "responsive": "SUB-14",
    "rwd": "SUB-14",
    "sub-14": "SUB-14",
    "visual": "SUB-15",
    "vis": "SUB-15",
    "sub-15": "SUB-15",
}


def resolve_subsystem_id(name_or_id: str) -> Optional[str]:
    """Resolves human name, alias, or ID to canonical SUB-XX ID."""
    clean = name_or_id.strip().lower()
    return NAME_TO_ID_MAP.get(clean)
